### ISSUE TITLE
code block syntax highlighting

### ISSUE THREAD

**Issue by dstokes** [8bitDesigner/better-unix-manuals#2]
could use something like: http://alexgorbatchev.com/SyntaxHighlighter/manual/brushes/bash.html

i need to read up again on how to do js in chrome extensions

**Comment by 8bitDesigner** [comment]
Here's an example from my BlindHire repo: https://github.com/8bitDesigner/BlindHired/blob/master/manifest.json

Add a `js` key to the manifest and point it to a file.
